#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2012 by Delphix. All rights reserved.
#

[DEFAULT]
pre =
verbose = False
quiet = False
timeout = 60
post =
outputdir = /var/tmp/test_results

[/opt/os-tests/tests/poll_test]
user = root

[/opt/os-tests/tests/sigqueue]
tests = ['sigqueue_queue_size']

[/opt/os-tests/tests/periodic/absolute]
[/opt/os-tests/tests/periodic/badargs]
[/opt/os-tests/tests/periodic/cancel]
[/opt/os-tests/tests/periodic/interleave]
[/opt/os-tests/tests/periodic/interval]
[/opt/os-tests/tests/periodic/oneshot]
[/opt/os-tests/tests/periodic/periodic]
[/opt/os-tests/tests/periodic/reschedule]
[/opt/os-tests/tests/periodic/stress]
